# -*- coding: utf-8 -*-
"""
/***************************************************************************
 wtyczkaDialog
                                 A QGIS plugin
 wtyczka
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-03
        git sha              : $Format:%H$
        copyright            : (C) 2024 by sss
        email                : ads
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from qgis.core import *
#import qgis.utils
from qgis.utils import iface

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'wtyczka_dialog_base.ui'))


class wtyczkaDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(wtyczkaDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        self.pushButton_dh.clicked.connect(self.calculate_dh)
        self.pushButton_pole.clicked.connect(self.calculate_area)
        self.pushButton_zlicz.clicked.connect(self.count_objects)
        self.buttonBox.accepted.connect(self.accept)
        self.buttonBox.rejected.connect(self.reject)
        
    def calculate_dh(self):
        current_layer = self.combo_box.currentLayer()
        selected_features = current_layer.selectedFeatures()
        h_1 = float(selected_features[0]['wysokosc'])
        h_2 = float(selected_features[1]['wysokosc'])
        P1 = selected_features[0]['nr_punktu']
        P2 = selected_features[1]['nr_punktu']
        d_h = h_2 - h_1
        self.label_wynik_dh.setText(f'{d_h:.3f} m')
        iface.messageBar().pushMessage("Obliczono", f"Różnica przewyższeń między punktami {P1} i {P2} wynosi {d_h:.3f}", level= Qgis.Success, duration=7)
        
    def podaj_dane_o_zaznaczonym_obiekcie(self):
        active_layer = iface.activeLayer()
        selected_features = active_layer.selectedFeatures()
        for feature in selected_features:
            geom = feature.geometry()
            geomSingleType = QgsWkbTypes.isSingleType(geom.wkbType())
            if geom.type() == QgsWkbTypes.PointGeometry:
                if geomSingleType:
                    x = geom.asPoint()
                    self.listaWybranychOb_wsp.append(f'Point: {x}, \r\n')
                else:
                    x = geom.asMultiPoint()
                    self.listaWybranychOb_wsp.append(f'MultiPoint: {x}, \r\n')
    
            elif geom.type() == QgsWkbTypes.LineGeometry:
                if geomSingleType:
                    x = geom.asPolyline()
                    self.listaWybranychOb_wsp.append(f'Line: {x}, \r\n')
                else:
                    x = geom.asMultiPolyline()
                    self.listaWybranychOb_wsp.append(f'Multiline: {x}, \r\n')
    
            elif geom.type() == QgsWkbTypes.PolygonGeometry:
                if geomSingleType:
                    x = geom.asPolygon()
                    self.listaWybranychOb_wsp.append(f'Polygon: {x} \r\n')
                else:
                    x = geom.asMultiPolygon()
                    self.listaWybranychOb_wsp.append(f'MultiPolygon: {x} \r\n')
            else:
                print("Unknown or invalid geometry")

     
        
    def calculate_area(self):
        # current_layer = self.combo_box.currentLayer()
        # selected_features = current_layer.selectedFeatures()
        # P2 = (X + Xn) * (Yn - Y)
        # P = P/2
        pass
    
    def count_objects(self):
        current_layer = self.combo_box.currentLayer()
        obj_number = current_layer.featureCount()
        self.label_wynik_obiekty.setText(str(obj_number))