# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wtyczka_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_wtyczkaDialogBase(object):
    def setupUi(self, wtyczkaDialogBase):
        wtyczkaDialogBase.setObjectName("wtyczkaDialogBase")
        wtyczkaDialogBase.resize(432, 597)
        self.combo_box = QgsMapLayerComboBox(wtyczkaDialogBase)
        self.combo_box.setGeometry(QtCore.QRect(170, 20, 151, 27))
        self.combo_box.setObjectName("combo_box")
        self.label_przewyzszenie_wynik = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_przewyzszenie_wynik.setGeometry(QtCore.QRect(70, 400, 131, 21))
        self.label_przewyzszenie_wynik.setObjectName("label_przewyzszenie_wynik")
        self.pushButton_dh = QtWidgets.QPushButton(wtyczkaDialogBase)
        self.pushButton_dh.setGeometry(QtCore.QRect(70, 350, 111, 23))
        self.pushButton_dh.setObjectName("pushButton_dh")
        self.label_wynik_dh = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_wynik_dh.setGeometry(QtCore.QRect(190, 400, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_wynik_dh.setFont(font)
        self.label_wynik_dh.setText("")
        self.label_wynik_dh.setObjectName("label_wynik_dh")
        self.buttonBox = QtWidgets.QDialogButtonBox(wtyczkaDialogBase)
        self.buttonBox.setGeometry(QtCore.QRect(240, 530, 161, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(False)
        self.buttonBox.setObjectName("buttonBox")
        self.label_wybierz_warstwe = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_wybierz_warstwe.setGeometry(QtCore.QRect(70, 0, 91, 61))
        self.label_wybierz_warstwe.setObjectName("label_wybierz_warstwe")
        self.pushButton_pole = QtWidgets.QPushButton(wtyczkaDialogBase)
        self.pushButton_pole.setGeometry(QtCore.QRect(210, 350, 111, 23))
        self.pushButton_pole.setObjectName("pushButton_pole")
        self.label_wynik_pole = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_wynik_pole.setGeometry(QtCore.QRect(190, 430, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_wynik_pole.setFont(font)
        self.label_wynik_pole.setText("")
        self.label_wynik_pole.setObjectName("label_wynik_pole")
        self.label_pole_wynik = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_pole_wynik.setGeometry(QtCore.QRect(70, 430, 131, 21))
        self.label_pole_wynik.setObjectName("label_pole_wynik")
        self.pushButton_zlicz = QtWidgets.QPushButton(wtyczkaDialogBase)
        self.pushButton_zlicz.setGeometry(QtCore.QRect(170, 60, 91, 23))
        self.pushButton_zlicz.setObjectName("pushButton_zlicz")
        self.label_obiekty = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_obiekty.setGeometry(QtCore.QRect(70, 100, 171, 21))
        self.label_obiekty.setObjectName("label_obiekty")
        self.label_wynik_obiekty = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_wynik_obiekty.setGeometry(QtCore.QRect(250, 100, 141, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_wynik_obiekty.setFont(font)
        self.label_wynik_obiekty.setText("")
        self.label_wynik_obiekty.setObjectName("label_wynik_obiekty")
        self.lista_wsp = QtWidgets.QTextEdit(wtyczkaDialogBase)
        self.lista_wsp.setGeometry(QtCore.QRect(70, 180, 311, 101))
        self.lista_wsp.setObjectName("lista_wsp")
        self.label_obiekty_wsp = QtWidgets.QLabel(wtyczkaDialogBase)
        self.label_obiekty_wsp.setGeometry(QtCore.QRect(70, 150, 171, 21))
        self.label_obiekty_wsp.setObjectName("label_obiekty_wsp")
        self.pushButton_pokaz = QtWidgets.QPushButton(wtyczkaDialogBase)
        self.pushButton_pokaz.setGeometry(QtCore.QRect(170, 290, 91, 23))
        self.pushButton_pokaz.setObjectName("pushButton_pokaz")

        self.retranslateUi(wtyczkaDialogBase)
        QtCore.QMetaObject.connectSlotsByName(wtyczkaDialogBase)

    def retranslateUi(self, wtyczkaDialogBase):
        _translate = QtCore.QCoreApplication.translate
        wtyczkaDialogBase.setWindowTitle(_translate("wtyczkaDialogBase", "wtyczka"))
        self.label_przewyzszenie_wynik.setText(_translate("wtyczkaDialogBase", "Przewyższenie wynosi"))
        self.pushButton_dh.setText(_translate("wtyczkaDialogBase", "Oblicz dh"))
        self.label_wybierz_warstwe.setText(_translate("wtyczkaDialogBase", "Wybierz warstwę"))
        self.pushButton_pole.setText(_translate("wtyczkaDialogBase", "Oblicz pole"))
        self.label_pole_wynik.setText(_translate("wtyczkaDialogBase", "Pole powierzchni  wynosi"))
        self.pushButton_zlicz.setText(_translate("wtyczkaDialogBase", "Zlicz"))
        self.label_obiekty.setText(_translate("wtyczkaDialogBase", "Liczba obiektów na warstwie wynosi:"))
        self.label_obiekty_wsp.setText(_translate("wtyczkaDialogBase", "Współrzędne wybranych obiektów:"))
        self.pushButton_pokaz.setText(_translate("wtyczkaDialogBase", "Pokaż"))
from qgsmaplayercombobox import QgsMapLayerComboBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    wtyczkaDialogBase = QtWidgets.QDialog()
    ui = Ui_wtyczkaDialogBase()
    ui.setupUi(wtyczkaDialogBase)
    wtyczkaDialogBase.show()
    sys.exit(app.exec_())
